language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python nba.py
before_install:
- openssl aes-256-cbc -K $encrypted_1e355175b3f4_key -iv $encrypted_1e355175b3f4_iv
  -in config.json.enc -out config.json -d
